// This file is auto-replaced when connected to Airtable API.
// Structure mirrors the Airtable fields exactly.

export const CATEGORIES = [
  "Gaming",
  "Social Media",
  "Safety",
  "Digital Relationships",
  "AI & Chatbots",
];

export const AGE_GROUPS = [
  { label: "Early Years", range: "3-5" },
  { label: "Primary",     range: "6-8" },
  { label: "Pre-Teen",    range: "9-11" },
  { label: "Early Teen",  range: "12-14" },
  { label: "Teen",        range: "15-17" },
];

export const RECORDS = [
  {
    id: "STG-0001",
    scenario: "Child talking to strangers in games",
    category: "Gaming",
    ageGroup: "Early Years",
    ageRange: "3-5",
    introLine: "Children aged 3–5 can encounter other players in games without parents realising the feature exists.",
    issue: "Many tablet and TV games that appear closed actually include community or messaging features. Young children have no concept of 'stranger danger' in a digital context — everyone who speaks to them feels like a potential friend.",
    whyItMatters: "At this age, children are completely trusting and have no filter for adult intent. Even short, friendly exchanges can be an early step in building inappropriate familiarity. Adults do target young children through gaming platforms, and children this age will rarely report it without prompting.",
    whatParentsCan: "Check every game your child plays for chat or community features — look in the settings menu, not just the app description. Use your device's parental controls to block all online communication. Play the game yourself briefly. Make sitting with your child while they play a regular habit rather than an exception.",
    whatChildrenCan: "Children aged 3–5 aren't ready for online safety conversations in the traditional sense. Focus on one simple real-world rule: 'We only talk to people we know.' Praise them immediately whenever they show you something new on a screen.",
    conversationStarters: "'Who's your favourite character in that game?' / 'Does anyone ever talk to you when you're playing?' / 'If someone you didn't know said something in your game, would you come and tell me?' Keep it light and curious — not alarming.",
    irishSupport: "Webwise.ie — Ireland's Internet Safety Awareness Centre: webwise.ie\nISPCC Childline — 1800 66 66 00 — 24/7 support for children: childline.ie\nBarnardos Ireland — Family support services: barnardos.ie\nHSE Parenting — Digital wellbeing advice: hse.ie/parenting",
    furtherReading: "PEGI age ratings explained — pegi.info\nWebwise Gaming Safety Guide — webwise.ie/parents/gaming\nRoblox parental controls step-by-step — roblox.com/parents",
    sources: "WHO (2019). Gaming disorder. ICD-11.\nWebwise (2023). Young People and Gaming in Ireland.\nBarnardos Ireland (2022). Screen Time and Young Children.",
    status: "Published",
    version: "1.0",
    lastUpdated: "2026-07-08",
  },
  {
    id: "STG-0002",
    scenario: "Child talking to strangers in games",
    category: "Gaming",
    ageGroup: "Primary",
    ageRange: "6-8",
    introLine: "Children aged 6–8 are moving into multiplayer games where contact with strangers is possible and often not obvious to parents.",
    issue: "Games like Roblox and Minecraft include chat, friend requests, and voice features that are turned on by default. Children this age are social and want to make friends. They don't yet understand that someone friendly online could have harmful intentions.",
    whyItMatters: "Roblox in particular has been the subject of documented grooming cases in Ireland and the UK. Children at this age are trusting, eager to please, and unlikely to identify warning signs without prior guidance from a parent.",
    whatParentsCan: "Enable Account Restrictions in Roblox. Turn off voice chat in Minecraft settings. Check your child's friends list together and make it feel normal rather than punitive. Play alongside them occasionally — you'll learn more about their online social world than any filter will tell you.",
    whatChildrenCan: "Teach three simple rules: don't share your real name, your school, or where you live. Practise what to say if someone asks — 'just say nothing and tell me.' Give them the words to exit: 'I have to go now.'",
    conversationStarters: "'Who did you play with today — anyone new?' / 'What would you do if someone in the game asked where you go to school?' / 'Has anyone ever said something in a game that felt a bit weird?'",
    irishSupport: "Webwise.ie — Ireland's Internet Safety Awareness Centre: webwise.ie\nISPCC Childline — 1800 66 66 00 — 24/7 support for children: childline.ie\nBarnardos Ireland — Family support services: barnardos.ie",
    furtherReading: "Webwise Gaming Safety Guide — webwise.ie/parents/gaming\nRoblox parental controls step-by-step — roblox.com/parents",
    sources: "Webwise (2023). Young People and Gaming in Ireland.\nISPCC (2023). Child Protection in the Digital Age.",
    status: "Published",
    version: "1.0",
    lastUpdated: "2026-07-08",
  },
  {
    id: "STG-0006",
    scenario: "Cyberbullying",
    category: "Safety",
    ageGroup: "Early Teen",
    ageRange: "12-14",
    introLine: "Cyberbullying in the early teen years often looks very different from what parents expect.",
    issue: "It's less 'mean messages' and more exclusion, screenshot-sharing, pile-ons, and subposting — posts clearly aimed at someone without naming them. It frequently moves between platforms, making it hard to escape.",
    whyItMatters: "Unlike schoolyard bullying, cyberbullying follows a child home and into their bedroom. It can happen at 2am. The audience can be their entire school. Ireland's Harmful Communications Act 2020 makes some forms of online harassment a criminal offence, but the emotional damage happens long before any legal process.",
    whatParentsCan: "Take it seriously immediately — don't minimise. Document everything with screenshots. Report to the platform and to the school. Contact An Garda Síochána if messages include threats or sexual content. Don't tell your child to 'just ignore it' — this doesn't work and makes them feel unheard.",
    whatChildrenCan: "Block and report — don't engage or retaliate. Save evidence. Tell a trusted adult, not just a friend. Know that this is not your fault and it is not a reflection of your worth.",
    conversationStarters: "'Have you ever seen someone treated badly online?' / 'Has anything online made you feel targeted or left out?' / 'If something like that happened to you, would you feel OK telling me?' / 'What would you do if a friend asked you to share something about someone else?'",
    irishSupport: "ISPCC Childline — 1800 66 66 00: childline.ie\nHotline.ie — Report illegal online content: hotline.ie\nWebwise.ie — Online safety reporting guides: webwise.ie\nAn Garda Síochána — Report online abuse: reportabuse.ie\nJigsaw — Youth mental health support: jigsaw.ie",
    furtherReading: "Webwise Anti-Bullying Resources — webwise.ie/parents/cyberbullying\nHarmful Communications Act 2020 — irishstatutebook.ie\nIreland's Digital Safety Commissioner — onlinesafety.ie",
    sources: "Webwise (2023). Cyberbullying in Ireland: Schools and Families.\nHarmful Communications and Related Offences Act 2020.\nISPCC (2022). Children's Experiences of Online Peer Pressure.",
    status: "Published",
    version: "1.0",
    lastUpdated: "2026-07-08",
  },
  {
    id: "STG-0009",
    scenario: "Using AI for homework",
    category: "AI & Chatbots",
    ageGroup: "Early Teen",
    ageRange: "12-14",
    introLine: "Early teens are using AI tools to complete homework — and most don't see it as cheating.",
    issue: "Children aged 12–14 are using ChatGPT, Google Gemini, and Copilot to write essays and answer exam questions. Many see AI as a tool, the same way a calculator is a tool — and they're not entirely wrong, but the line matters.",
    whyItMatters: "AI-generated work bypasses the learning process entirely. A child who uses AI to write an essay hasn't practised thinking, arguing, or expressing themselves. These are skills they'll need. Schools in Ireland are increasingly detecting AI use and implementing academic consequences.",
    whatParentsCan: "Have a values conversation rather than a rules conversation. Ask what they think the difference is between using AI and learning. Agree a household position together. If they're using AI because work feels overwhelming, that's a different conversation — about pressure, not technology.",
    whatChildrenCan: "Use AI as a thinking partner, not an answer machine: ask it to explain a concept and then write the answer in your own words. This builds skills while using the tool appropriately.",
    conversationStarters: "'Have you used AI for any homework recently?' / 'What do you think the difference is between using AI and using a dictionary?' / 'What happens if your teacher can tell?' / 'Is there any work that's feeling really hard at the moment?'",
    irishSupport: "Webwise.ie — AI literacy resources: webwise.ie\nISPCC Childline — 1800 66 66 00: childline.ie\nSpunOut.ie — Youth guide to misinformation and AI: spunout.ie\nPDST Digital Literacy — School resources: pdst.ie",
    furtherReading: "Webwise AI Guide for Parents — webwise.ie/parents/ai\nCommon Sense Media AI explainers — commonsensemedia.org/ai\nDept. of Education Digital Strategy for Schools 2027",
    sources: "Department of Education Ireland (2023). Digital Strategy for Schools 2027.\nCommon Sense Media (2023). AI and the Future of Learning.\nWebwise (2024). Artificial Intelligence: A Guide for Parents.",
    status: "Published",
    version: "1.0",
    lastUpdated: "2026-07-08",
  },
];
